import { useState, useEffect, useRef, useCallback } from "react";
import { patchWsDebug, getWsDebug } from "@/lib/wsDebugStore";

// ── Server message types ───────────────────────────────────────────────────────
//
// The server is a pure price relay — it sends raw trade prices, NOT synthetic OHLC.
// Clients build candles themselves from the price stream.

export interface PriceUpdate {
  type: "price.update";
  symbol: string;
  price: number;
  timestamp: number; // Unix seconds
}

export interface MarketStatus {
  type: "market.status";
  symbol: string;
  isOpen: boolean;
  price: number;
  lastClose: number;
  timestamp?: number;
}

export interface MarketCapability {
  type: "market.capability";
  symbol: string;
  realtimeAvailable: boolean;
  reason: "plan_limit" | null;
}

export interface SignalNew {
  type: "signal.new";
  signalId: string;
  symbol: string;
  side: "long" | "short";
  entryPrice: number;
  slPrice: number;
  tpPrice: number;
  confidence: number;
  riskTag: string;
  barTime: string;
  grade?: "A+" | "A" | "B" | "Weak";
  patterns?: string[];
  // Historical lifecycle info (present for backtested signals; omitted for live WS signals)
  state?: "active" | "tp_hit" | "sl_hit" | "expired";
  exitPrice?: number | null;
  exitBarTime?: string | null;
  exitReason?: string | null;
  // AI Decision Engine — present only for signals generated by POST /ai/decide
  isAiSignal?: boolean;
  aiReasoning?: string;
  aiMarketBias?: string;
}

export interface SlUpdate {
  type: "sl.update";
  signalId: string;
  slPrice: number;
}

export interface SignalExit {
  type: "signal.exit";
  signalId: string;
  reason: string;
  exitPrice: number;
  barTime: string;
}

export type MarketEvent =
  | PriceUpdate
  | MarketStatus
  | MarketCapability
  | SignalNew
  | SlUpdate
  | SignalExit;

interface UseMarketSocketResult {
  connected: boolean;
  lastPrice: PriceUpdate | null;
  isMarketOpen: boolean;
  marketPrice: number | null;
  // True until the server tells us otherwise (e.g. data-provider plan with no
  // WS access). When false the chart should show "historical only" and stop
  // expecting live updates.
  realtimeAvailable: boolean;
  newSignals: SignalNew[];
  slUpdates: SlUpdate[];
  signalExits: SignalExit[];
  // Debug counter — total messages received since mount
  msgCount: number;
}

export function useMarketSocket(symbol: string | null): UseMarketSocketResult {
  const [connected,    setConnected]    = useState(false);
  const [lastPrice,    setLastPrice]    = useState<PriceUpdate | null>(null);
  const [isMarketOpen, setIsMarketOpen] = useState<boolean>(false);
  const [marketPrice,  setMarketPrice]  = useState<number | null>(null);
  const [realtimeAvailable, setRealtimeAvailable] = useState<boolean>(true);
  const [newSignals,   setNewSignals]   = useState<SignalNew[]>([]);
  const [slUpdates,    setSlUpdates]    = useState<SlUpdate[]>([]);
  const [signalExits,  setSignalExits]  = useState<SignalExit[]>([]);
  const [msgCount,     setMsgCount]     = useState(0);

  const wsRef          = useRef<WebSocket | null>(null);
  const reconnectTimer = useRef<ReturnType<typeof setTimeout> | null>(null);
  const msgCountRef    = useRef(0);

  const connect = useCallback(() => {
    if (!symbol) return;
    if (wsRef.current) wsRef.current.close();

    const protocol = window.location.protocol === "https:" ? "wss:" : "ws:";
    const host     = window.location.host;
    const base     = import.meta.env.BASE_URL?.replace(/\/$/, "") ?? "";
    const url      = `${protocol}//${host}${base}/ws?symbol=${encodeURIComponent(symbol)}`;

    console.log(`[WS] Connecting to ${url}`);
    const ws = new WebSocket(url);
    wsRef.current = ws;

    ws.onopen = () => {
      if (ws !== wsRef.current) return;
      console.log(`[WS] Connected — symbol=${symbol}`);
      setConnected(true);
      if (reconnectTimer.current) {
        clearTimeout(reconnectTimer.current);
        reconnectTimer.current = null;
      }
    };

    ws.onmessage = (ev) => {
      if (ws !== wsRef.current) return;
      try {
        const msg = JSON.parse(ev.data) as MarketEvent;

        // Track every message in the debug store
        msgCountRef.current += 1;
        const count = msgCountRef.current;
        setMsgCount(count);

        const prev = getWsDebug();
        patchWsDebug({
          frontendMsgCount: count,
          lastMsgTime:      Date.now(),
          lastSymbol:       "symbol" in msg ? (msg as { symbol?: string }).symbol ?? prev.lastSymbol : prev.lastSymbol,
          lastPrice:        msg.type === "price.update"
            ? (msg as PriceUpdate).price
            : msg.type === "market.status"
            ? (msg as MarketStatus).price || prev.lastPrice
            : prev.lastPrice,
        });

        // Verbose console log for every message (throttle price.update to every 10th)
        if (msg.type === "price.update") {
          if (count % 10 === 1) {
            console.log(`[WS] #${count} price.update sym=${(msg as PriceUpdate).symbol} price=${(msg as PriceUpdate).price}`);
          }
        } else {
          console.log(`[WS] #${count} ${msg.type}`, msg);
        }

        switch (msg.type) {
          case "price.update": {
            const p = msg as PriceUpdate;
            if (p.price > 0) {
              setLastPrice(p);
              setIsMarketOpen(true);
              setMarketPrice(p.price);
            }
            break;
          }
          case "market.status": {
            const s = msg as MarketStatus;
            setIsMarketOpen(s.isOpen);
            console.log(`[WS] market.status isOpen=${s.isOpen} price=${s.price}`);
            if (s.price > 0) setMarketPrice(s.price);
            break;
          }
          case "market.capability": {
            const c = msg as MarketCapability;
            console.log(`[WS] market.capability realtimeAvailable=${c.realtimeAvailable} reason=${c.reason}`);
            setRealtimeAvailable(c.realtimeAvailable);
            break;
          }
          case "signal.new":
            setNewSignals((prev) => [msg as SignalNew, ...prev].slice(0, 20));
            break;
          case "sl.update":
            setSlUpdates((prev) => [msg as SlUpdate, ...prev].slice(0, 20));
            break;
          case "signal.exit":
            setSignalExits((prev) => [msg as SignalExit, ...prev].slice(0, 20));
            break;
        }
      } catch { /* ignore */ }
    };

    ws.onclose = (ev) => {
      if (ws !== wsRef.current) return;
      console.log(`[WS] Closed code=${ev.code} — reconnecting in 3 s`);
      setConnected(false);
      reconnectTimer.current = setTimeout(() => connect(), 3000);
    };

    ws.onerror = (ev) => {
      if (ws !== wsRef.current) return;
      console.error("[WS] Error", ev);
      ws.close();
    };
  }, [symbol]);

  useEffect(() => {
    connect();
    return () => {
      if (reconnectTimer.current) clearTimeout(reconnectTimer.current);
      if (wsRef.current) { wsRef.current.onclose = null; wsRef.current.close(); }
    };
  }, [connect]);

  useEffect(() => {
    setNewSignals([]);
    setSlUpdates([]);
    setSignalExits([]);
    msgCountRef.current = 0;
    setMsgCount(0);
  }, [symbol]);

  return {
    connected,
    lastPrice,
    isMarketOpen,
    marketPrice,
    realtimeAvailable,
    newSignals,
    slUpdates,
    signalExits,
    msgCount,
  };
}
